#!/bin/zsh
distributionConfig=$(jq "
.CallerReference=\"`uuidgen`\"
  | .ViewerCertificate.ACMCertificateArn=\"arn:aws:acm:us-east-1:552879364626:certificate/a22592bf-9325-45f0-947f-55ed4dd0ffdd\"
  " scripts/aws:cloudfront/distribution-config.json)
aws cloudfront create-distribution \
  --distribution-config file://<(echo $distributionConfig) | \
  jq .Distribution.Id -r | tr -d '\n' > scripts/aws:cloudfront/distribution-id
